/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ski.rental.system;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author chiahxuan
 */
public class admin_catalogue extends javax.swing.JFrame {

    /**
     * Creates new form admin_catalogue
     */
    public admin_catalogue() {
        initComponents();
    }
    
    public void setColor (JPanel panel ){
        panel.setBackground(new Color(3, 78, 109));
  
    }
    
    public void resetColor (JPanel panel ){
        panel.setBackground(new Color(2, 51, 71));
   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBar = new javax.swing.JPanel();
        btmLogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        PM_Dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab_product = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supplie = new javax.swing.JTable();
        tab_report = new javax.swing.JPanel();
        cbo_product = new javax.swing.JComboBox<>();
        cbo_reportType = new javax.swing.JComboBox<>();
        cbo_reports5 = new javax.swing.JComboBox<>();
        btn_print = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jdate_reportDate = new com.toedter.calendar.JDateChooser();
        btn_generate1 = new javax.swing.JButton();
        NavigationBar = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_viewCatalogue = new javax.swing.JPanel();
        lbl_manageCatalogue = new javax.swing.JLabel();
        lbl_catalogueIcon = new javax.swing.JLabel();
        btn_manageSupplier = new javax.swing.JPanel();
        lbl_productIcon = new javax.swing.JLabel();
        lbl_manageSupplier = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JPanel();
        lbl_dashboardIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_manageProfile = new javax.swing.JPanel();
        lbl_userIcon = new javax.swing.JLabel();
        lbl_manageProfile = new javax.swing.JLabel();
        btn_manageProduct = new javax.swing.JPanel();
        lbl_productIcon2 = new javax.swing.JLabel();
        lbl_manageProduct = new javax.swing.JLabel();
        btn_manageManager = new javax.swing.JPanel();
        lbl_productIcon1 = new javax.swing.JLabel();
        lbl_manageSupplier1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBar.setBackground(new java.awt.Color(2, 51, 71));
        TopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmLogout.setBackground(new java.awt.Color(2, 51, 71));
        btmLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btmLogout.setForeground(new java.awt.Color(255, 255, 255));
        btmLogout.setText("Logout");
        btmLogout.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), null));
        TopBar.add(btmLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 120, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/ski.png"))); // NOI18N
        jLabel6.setText("SkiInv.");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        TopBar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 90));

        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 90));

        PM_Dashboard.setBackground(new java.awt.Color(230, 234, 237));
        PM_Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(2, 51, 71));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 51, 71));
        jLabel3.setText("Catalogue");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PM_Dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 50));

        tab_product.setForeground(new java.awt.Color(2, 51, 71));
        tab_product.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_product.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        tbl_supplie.setAutoCreateRowSorter(true);
        tbl_supplie.setBackground(new java.awt.Color(255, 255, 255));
        tbl_supplie.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tbl_supplie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category ID", "Category Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_supplie.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_supplie.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane1.setViewportView(tbl_supplie);

        tab_product.addTab("Catalogue", jScrollPane1);

        tab_report.setBackground(new java.awt.Color(255, 255, 255));
        tab_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbo_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tab_report.add(cbo_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 192, 30));

        cbo_reportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tab_report.add(cbo_reportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 192, 30));

        cbo_reports5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tab_report.add(cbo_reports5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 192, 30));

        btn_print.setBackground(new java.awt.Color(234, 63, 63));
        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.setBorder(null);
        tab_report.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 140, 40));

        btn_reset.setBackground(new java.awt.Color(234, 63, 63));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.setBorder(null);
        tab_report.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 140, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tab_report.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 20, 190));
        tab_report.add(jdate_reportDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, -1));

        btn_generate1.setBackground(new java.awt.Color(234, 63, 63));
        btn_generate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_generate1.setForeground(new java.awt.Color(255, 255, 255));
        btn_generate1.setText("Generate");
        btn_generate1.setBorder(null);
        tab_report.add(btn_generate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, 40));

        tab_product.addTab("Report", tab_report);

        PM_Dashboard.add(tab_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 790, 370));

        getContentPane().add(PM_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 840, 510));

        NavigationBar.setBackground(new java.awt.Color(2, 51, 71));
        NavigationBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(2, 51, 71));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Search something here...");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        NavigationBar.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/search .png"))); // NOI18N
        NavigationBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        btn_viewCatalogue.setBackground(new java.awt.Color(234, 63, 63));
        btn_viewCatalogue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewCatalogueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewCatalogueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_viewCatalogueMousePressed(evt);
            }
        });
        btn_viewCatalogue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageCatalogue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_manageCatalogue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageCatalogue.setText("View Catalogue");
        lbl_manageCatalogue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageCatalogueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageCatalogueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_manageCatalogueMousePressed(evt);
            }
        });
        btn_viewCatalogue.add(lbl_manageCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        lbl_catalogueIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_catalogueIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/catalogue.png"))); // NOI18N
        btn_viewCatalogue.add(lbl_catalogueIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        NavigationBar.add(btn_viewCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 50));

        btn_manageSupplier.setBackground(new java.awt.Color(2, 51, 71));
        btn_manageSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manageSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manageSupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_manageSupplierMousePressed(evt);
            }
        });
        btn_manageSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_productIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_productIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/supplier.png"))); // NOI18N
        btn_manageSupplier.add(lbl_productIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        lbl_manageSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_manageSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageSupplier.setText("Manage Supplier");
        btn_manageSupplier.add(lbl_manageSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 50));

        NavigationBar.add(btn_manageSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));

        btn_dashboard.setBackground(new java.awt.Color(2, 51, 71));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashboardMousePressed(evt);
            }
        });
        btn_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashboardIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_dashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/statistics_32px.png"))); // NOI18N
        btn_dashboard.add(lbl_dashboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        btn_dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        NavigationBar.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 50));

        btn_manageProfile.setBackground(new java.awt.Color(2, 51, 71));
        btn_manageProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manageProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manageProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manageProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_manageProfileMousePressed(evt);
            }
        });
        btn_manageProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_userIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/user32.png"))); // NOI18N
        btn_manageProfile.add(lbl_userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        lbl_manageProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_manageProfile.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageProfile.setText("Manage Profile");
        btn_manageProfile.add(lbl_manageProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        NavigationBar.add(btn_manageProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 50));

        btn_manageProduct.setBackground(new java.awt.Color(2, 51, 71));
        btn_manageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manageProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manageProductMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_manageProductMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_manageProductMouseReleased(evt);
            }
        });
        btn_manageProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_productIcon2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_productIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/product.png"))); // NOI18N
        btn_manageProduct.add(lbl_productIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        lbl_manageProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_manageProduct.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageProduct.setText("Manage Product");
        btn_manageProduct.add(lbl_manageProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 50));

        NavigationBar.add(btn_manageProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        btn_manageManager.setBackground(new java.awt.Color(2, 51, 71));
        btn_manageManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manageManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manageManagerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_manageManagerMousePressed(evt);
            }
        });
        btn_manageManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_productIcon1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_productIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/manager_32px.png"))); // NOI18N
        btn_manageManager.add(lbl_productIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        lbl_manageSupplier1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_manageSupplier1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageSupplier1.setText("Manage Manager");
        btn_manageManager.add(lbl_manageSupplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 50));

        NavigationBar.add(btn_manageManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 50));

        getContentPane().add(NavigationBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        //***check for role for navigation *****
        //if(role = admin){go admin dashboard}else {go pm dashboard}
        this.setVisible(false);
        new pm_dashboard().setVisible(true);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lbl_manageCatalogueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageCatalogueMouseEntered

    }//GEN-LAST:event_lbl_manageCatalogueMouseEntered

    private void lbl_manageCatalogueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageCatalogueMouseExited

    }//GEN-LAST:event_lbl_manageCatalogueMouseExited

    private void lbl_manageCatalogueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageCatalogueMousePressed

    }//GEN-LAST:event_lbl_manageCatalogueMousePressed

    private void btn_viewCatalogueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewCatalogueMouseEntered
    }//GEN-LAST:event_btn_viewCatalogueMouseEntered

    private void btn_viewCatalogueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewCatalogueMouseExited
    }//GEN-LAST:event_btn_viewCatalogueMouseExited

    private void btn_viewCatalogueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewCatalogueMousePressed
    }//GEN-LAST:event_btn_viewCatalogueMousePressed

    private void btn_manageSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageSupplierMouseEntered
        // TODO add your handling code here:
        setColor(btn_manageSupplier);
    }//GEN-LAST:event_btn_manageSupplierMouseEntered

    private void btn_manageSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageSupplierMouseExited
        // TODO add your handling code here:
        resetColor(btn_manageSupplier);
    }//GEN-LAST:event_btn_manageSupplierMouseExited

    private void btn_manageSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageSupplierMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_supplier().setVisible(true);
    }//GEN-LAST:event_btn_manageSupplierMousePressed

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        setColor(btn_dashboard);
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        resetColor(btn_dashboard);
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardMousePressed

    private void btn_manageProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProfileMouseClicked

    }//GEN-LAST:event_btn_manageProfileMouseClicked

    private void btn_manageProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProfileMouseEntered
        setColor(btn_manageProfile);
    }//GEN-LAST:event_btn_manageProfileMouseEntered

    private void btn_manageProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProfileMouseExited
        resetColor(btn_manageProfile);
    }//GEN-LAST:event_btn_manageProfileMouseExited

    private void btn_manageProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProfileMousePressed
        this.setVisible(false);
        new admin_profile().setVisible(true);
    }//GEN-LAST:event_btn_manageProfileMousePressed

    private void btn_manageProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProductMouseEntered
        // TODO add your handling code here:
        setColor(btn_manageProduct);
    }//GEN-LAST:event_btn_manageProductMouseEntered

    private void btn_manageProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProductMouseExited
        // TODO add your handling code here:
        resetColor(btn_manageProduct);
    }//GEN-LAST:event_btn_manageProductMouseExited

    private void btn_manageProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProductMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_product().setVisible(true);
    }//GEN-LAST:event_btn_manageProductMousePressed

    private void btn_manageProductMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageProductMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_manageProductMouseReleased

    private void btn_manageManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageManagerMouseEntered
        // TODO add your handling code here:
        setColor(btn_manageManager);
    }//GEN-LAST:event_btn_manageManagerMouseEntered

    private void btn_manageManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageManagerMouseExited
        // TODO add your handling code here:
        resetColor(btn_manageManager);
    }//GEN-LAST:event_btn_manageManagerMouseExited

    private void btn_manageManagerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageManagerMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_manager().setVisible(true);
    }//GEN-LAST:event_btn_manageManagerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_catalogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavigationBar;
    private javax.swing.JPanel PM_Dashboard;
    private javax.swing.JPanel TopBar;
    private javax.swing.JButton btmLogout;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JButton btn_generate1;
    private javax.swing.JPanel btn_manageManager;
    private javax.swing.JPanel btn_manageProduct;
    private javax.swing.JPanel btn_manageProfile;
    private javax.swing.JPanel btn_manageSupplier;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_reset;
    private javax.swing.JPanel btn_viewCatalogue;
    private javax.swing.JComboBox<String> cbo_product;
    private javax.swing.JComboBox<String> cbo_reportType;
    private javax.swing.JComboBox<String> cbo_reports5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser jdate_reportDate;
    private javax.swing.JLabel lbl_catalogueIcon;
    private javax.swing.JLabel lbl_dashboardIcon;
    private javax.swing.JLabel lbl_manageCatalogue;
    private javax.swing.JLabel lbl_manageProduct;
    private javax.swing.JLabel lbl_manageProfile;
    private javax.swing.JLabel lbl_manageSupplier;
    private javax.swing.JLabel lbl_manageSupplier1;
    private javax.swing.JLabel lbl_productIcon;
    private javax.swing.JLabel lbl_productIcon1;
    private javax.swing.JLabel lbl_productIcon2;
    private javax.swing.JLabel lbl_userIcon;
    private javax.swing.JTabbedPane tab_product;
    private javax.swing.JPanel tab_report;
    private javax.swing.JTable tbl_supplie;
    // End of variables declaration//GEN-END:variables
}
