/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ski.rental.system;

/**
 *
 * @author chiahxuan
 */
public class template_addOrEdit extends javax.swing.JFrame {

    /**
     * Creates new form template_addOrEdit
     */
    public template_addOrEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PM_Dashboard = new javax.swing.JPanel();
        lbl_passwordReset = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_role = new javax.swing.JLabel();
        lbl_username2 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ps_newPassword = new javax.swing.JPasswordField();
        lbl_username1 = new javax.swing.JLabel();
        pw_reconfirmPassword = new javax.swing.JPasswordField();
        lbl_password2 = new javax.swing.JLabel();
        btn_confirm1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PM_Dashboard.setBackground(new java.awt.Color(230, 234, 237));
        PM_Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_passwordReset.setBackground(new java.awt.Color(2, 51, 71));
        lbl_passwordReset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_passwordReset.setForeground(new java.awt.Color(2, 51, 71));
        lbl_passwordReset.setText("Create Password");
        lbl_passwordReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PM_Dashboard.add(lbl_passwordReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 330, 50));

        lbl_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(2, 51, 71));
        lbl_password.setText("New Password");
        PM_Dashboard.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        PM_Dashboard.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 170, -1));

        lbl_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(2, 51, 71));
        lbl_email.setText("Email: ");
        PM_Dashboard.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btn_reset.setBackground(new java.awt.Color(234, 63, 63));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.setBorder(null);
        PM_Dashboard.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 140, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PM_Dashboard.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 30, 360));

        lbl_role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_role.setForeground(new java.awt.Color(2, 51, 71));
        lbl_role.setText("Role: ");
        PM_Dashboard.add(lbl_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lbl_username2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username2.setForeground(new java.awt.Color(2, 51, 71));
        lbl_username2.setText("Contact: ");
        PM_Dashboard.add(lbl_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txt_contact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        PM_Dashboard.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 170, -1));

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(2, 51, 71));
        lbl_id.setText("ID: ");
        PM_Dashboard.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txt_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        PM_Dashboard.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(2, 51, 71));
        lbl_name.setText("Name: ");
        PM_Dashboard.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        PM_Dashboard.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        txt_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        PM_Dashboard.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, -1));

        jLabel4.setBackground(new java.awt.Color(2, 51, 71));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 51, 71));
        jLabel4.setText("Manage Profile");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PM_Dashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 50));

        ps_newPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        PM_Dashboard.add(ps_newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 170, -1));

        lbl_username1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username1.setForeground(new java.awt.Color(2, 51, 71));
        lbl_username1.setText("Username: ");
        PM_Dashboard.add(lbl_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        pw_reconfirmPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        PM_Dashboard.add(pw_reconfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 170, -1));

        lbl_password2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_password2.setForeground(new java.awt.Color(2, 51, 71));
        lbl_password2.setText("Reconfirm Password");
        PM_Dashboard.add(lbl_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        btn_confirm1.setBackground(new java.awt.Color(234, 63, 63));
        btn_confirm1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_confirm1.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirm1.setText("Add / Edit");
        btn_confirm1.setBorder(null);
        PM_Dashboard.add(btn_confirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 140, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager" }));
        PM_Dashboard.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PM_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PM_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(template_addOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(template_addOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(template_addOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(template_addOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new template_addOrEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PM_Dashboard;
    private javax.swing.JButton btn_confirm1;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_password2;
    private javax.swing.JLabel lbl_passwordReset;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_username1;
    private javax.swing.JLabel lbl_username2;
    private javax.swing.JPasswordField ps_newPassword;
    private javax.swing.JPasswordField pw_reconfirmPassword;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
