/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ski.rental.system;

/**
 *
 * @author chiahxuan
 */
public class template_confirmation extends javax.swing.JFrame {

    /**
     * Creates new form template_confirmation
     */
    public template_confirmation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        whitearea = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(230, 234, 237));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        whitearea.setBackground(java.awt.Color.white);
        whitearea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/export_50px.png"))); // NOI18N
        whitearea.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 60));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 51, 71));
        jLabel1.setText("Are you sure you want to ____?");
        whitearea.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 310, 30));

        btn_cancel.setBackground(new java.awt.Color(234, 63, 63));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/delete_32px.png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(null);
        whitearea.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 40));

        btn_confirm.setBackground(new java.awt.Color(234, 63, 63));
        btn_confirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_confirm.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ski/rental/icons/Selected Images and icons/checkmark_26px.png"))); // NOI18N
        btn_confirm.setText("Confirm");
        btn_confirm.setBorder(null);
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        whitearea.add(btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 40));

        background.add(whitearea, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 73, 360, 210));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 51, 71));
        jLabel6.setText("Confirmation");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(template_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(template_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(template_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(template_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new template_confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JPanel whitearea;
    // End of variables declaration//GEN-END:variables
}
